global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'opensky-data-collector'
    static_configs:
      - targets: ['data-collector:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'opensky-spark'
    static_configs:
      - targets: ['spark-master:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'opensky-airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    scrape_interval: 30s
    metrics_path: /admin/metrics

  - job_name: 'system-metrics'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s
